#VEHICLE
DRIVE_LOOP_HZ = 20
MAX_LOOPS = 100000

#CAMERA
CAMERA_RESOLUTION = (120, 160) #(height, width)
CAMERA_FRAMERATE = DRIVE_LOOP_HZ

#STEERING
STEERING_CHANNEL = 1
STEERING_LEFT_PWM = 480
STEERING_RIGHT_PWM = 310

#THROTTLE
THROTTLE_CHANNEL = 0
THROTTLE_FORWARD_PWM = 395
THROTTLE_STOPPED_PWM = 360
THROTTLE_REVERSE_PWM = 330

#TRAINING
BATCH_SIZE = 128
TRAIN_TEST_SPLIT = 0.8


#JOYSTICK
USE_JOYSTICK_AS_DEFAULT = False
JOYSTICK_MAX_THROTTLE = 0.25
JOYSTICK_STEERING_SCALE = 1.0
AUTO_RECORD_ON_THROTTLE = True

#ROPE.tortue_rapide.COM
ROPE_TOKEN = "GET A TOKEN AT ROPE.tortue_rapide.COM"
